# Starter pipeline
# Start with a minimal pipeline that you can customize to build and deploy your code.
# Add steps that build, run tests, deploy, and more:
# https://aka.ms/yaml //first 

trigger:
  - main

pool:
  vmImage: 'ubuntu-latest'

steps:
  - task: Checkout@1

  - script: echo "Running CI build..."
    displayName: "Build Step"

  - script: echo "Running tests..."
    displayName: "Test Step"
#finish